/**
 * Typed Astro locals for Cloudflare runtime.
 *
 * The global `Env` interface is generated by `pnpm cf:types` (wrangler types)
 * from wrangler.toml [vars]. Secrets and bindings not in wrangler.toml are
 * augmented here.
 *
 * In @astrojs/cloudflare v13+, environment variables are accessed via
 * `import { env } from 'cloudflare:workers'` rather than locals.runtime.env.
 *
 * @see https://developers.cloudflare.com/workers/runtime-apis/bindings/
 */

/** Augment the wrangler-generated Env with secrets and optional bindings. */
interface Env {
  /** Server-side API key for Appwrite (set via `wrangler secret put`). */
  APPWRITE_API_KEY?: string;
  /** Appwrite collection ID for the LiveStatus table. */
  APPWRITE_STATUS_TABLE_ID?: string;
}

declare namespace App {
  interface Locals extends import('@astrojs/cloudflare').Runtime {}
}
