/**
 * Typed Astro locals for Cloudflare runtime.
 *
 * The global `Env` interface is generated by `pnpm cf:types` (wrangler types)
 * from wrangler.toml [vars]. Secrets and bindings not in wrangler.toml are
 * augmented here so context.locals.runtime.env is fully typed.
 *
 * @see https://docs.astro.build/en/guides/integrations-guide/cloudflare/#typing
 */
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

/** Augment the wrangler-generated Env with secrets and optional bindings. */
interface Env {
  /** Server-side API key for Appwrite (set via `wrangler secret put`). */
  APPWRITE_API_KEY?: string;
  /** Appwrite collection ID for the LiveStatus table. */
  APPWRITE_STATUS_TABLE_ID?: string;
}

declare namespace App {
  interface Locals extends Runtime {}
}
