/**
 * Typed Astro locals for Cloudflare runtime.
 *
 * The global `Env` interface is generated by `pnpm cf:types` (wrangler types)
 * from wrangler.toml [vars]. Secrets and bindings not in wrangler.toml are
 * augmented here.
 *
 * In @astrojs/cloudflare v13+:
 *   - Environment variables: `import { env } from 'cloudflare:workers'`
 *   - Execution context:     `Astro.locals.cfContext`
 *   - cf object:             `Astro.request.cf`
 *   - The old `Astro.locals.runtime.env` API is removed.
 *
 * @see https://developers.cloudflare.com/workers/runtime-apis/bindings/
 */

/** Augment the wrangler-generated Env with secrets and optional bindings. */
interface Env {
  /** Server-side API key for Appwrite (set via `wrangler secret put`). */
  APPWRITE_API_KEY?: string;
  /** Appwrite collection ID for the LiveStatus table. */
  APPWRITE_STATUS_TABLE_ID?: string;
}

declare namespace App {
  /** Runtime.cfContext gives access to the Workers ExecutionContext. */
  interface Locals extends import('@astrojs/cloudflare').Runtime { }
}

/** Allow bare .wasm imports — @cloudflare/vite-plugin resolves them as WebAssembly.Module. */
declare module '*.wasm' {
  const mod: WebAssembly.Module;
  export default mod;
}
